# -*- coding: utf-8 -*-
"""latlong_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyoTOmH1gJrdtZZM8C265tt2oEsC-RDE
"""

import requests
import pandas as pd
import time
import random

# Read input data
df = pd.read_csv('gurgaon_properties_cleaned_v1.csv', usecols=['sector'])

# Function to get coordinates using Nominatim
def get_coordinates(sector):
    try:
        location = f"Sector {sector}, Gurgaon, India"
        url = "https://nominatim.openstreetmap.org/search"
        params = {
            'q': location,
            'format': 'json',
            'limit': 1
        }
        response = requests.get(url, params=params, headers={"User-Agent": "Mozilla/5.0"})
        data = response.json()

        if data:
            lat = data[0]['lat']
            lon = data[0]['lon']
            return f"{lat}, {lon}"
    except Exception as e:
        print(f"Error for {sector}: {e}")
    return None

# Create output DataFrame
output_df = pd.DataFrame(columns=["Sector", "Coordinates"])

# Loop with delay to avoid getting blocked
for sector in df['sector'].dropna().unique():
    print(f"Getting coordinates for Sector {sector}")
    coords = get_coordinates(sector)
    output_df = pd.concat([output_df, pd.DataFrame([{"Sector": sector, "Coordinates": coords}])])
    time.sleep(random.uniform(1.5, 3.0))  # Sleep to avoid rate-limiting

# Save to CSV
print("Task Completed ✅")

output_df.head()

output_df.to_csv("gurgaon_sectors_with_coordinates.csv", index=False)